name: Podman Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Build Container
      run: |
        podman build -t my-container .

    - name: Run Container
      run: |
        podman run -d -p 8080:80 my-container
